---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openvpn-server-certs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: openvpn-server
spec:
  data:
    - secretKey: LAB.VPN.KEMO.NETWORK.key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/services/openvpn-server # name of the secret under the target Vault path
        property: LAB_VPN_KEMO_NETWORK_key # # name of the key in that named Vault secret
    - secretKey: ca.crt # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/services/openvpn-server # name of the secret under the target Vault path
        property: ca_crt # # name of the key in that named Vault secret
    - secretKey: LAB.VPN.KEMO.NETWORK.crt # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/services/openvpn-server # name of the secret under the target Vault path
        property: LAB_VPN_KEMO_NETWORK_crt # # name of the key in that named Vault secret
    - secretKey: dh.pem # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/services/openvpn-server # name of the secret under the target Vault path
        property: dh_pem # # name of the key in that named Vault secret
    - secretKey: ta.key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/services/openvpn-server # name of the secret under the target Vault path
        property: ta_key # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openvpn-server-certs # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make
