---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-server
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: openvpn-server
spec:
  selector:
    matchLabels:
      app: openvpn-server
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: openvpn-server
    spec:
      containers:
        - name: openvpn-server
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: docker.io/kylemanna/openvpn:latest
          securityContext:
            sysctls:
              - name: net.ipv6.conf.default.forwarding
                value: "1"
              - name: net.ipv6.conf.all.forwarding
                value: "1"
              - name: net.ipv4.ip_forward
                value: "1"
            privileged: true
            capabilities:
              add:
                #- MKNOD
                - NET_ADMIN
          ports:
            - containerPort: 1194
          volumeMounts:
            - name: server-config
              mountPath: /etc/openvpn
            - name: openvpn-server-certs
              mountPath: /etc/openvpn/secrets
      volumes:
        - name: server-config
          configMap:
            name: openvpn-server-config
        - name: openvpn-server-certs
          secret:
            secretName: openvpn-server-certs
