---
apiVersion: v1
kind: Service
metadata:
  name: openvpn-server
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    metallb.universe.tf/loadBalancerIPs: 192.168.42.19
    metallb.universe.tf/address-pool: lab-pool
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.42.19"
  labels:
    app: openvpn-server
spec:
  ports:
    - port: 1194
      protocol: UDP
      targetPort: 1194
      name: ovpn-server-udp
  selector:
    app: openvpn-server
  type: LoadBalancer